services:
  - type: web
    name: video2minutes-api
    env: python
    rootDir: src/backend
    buildCommand: pip install -r ../../requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      
  - type: static
    name: video2minutes-frontend
    rootDir: src/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
    envVars:
      - key: VITE_API_URL
        value: https://video2minutes-api.onrender.com
      - key: VITE_WS_URL
        value: wss://video2minutes-api.onrender.com